name: integrate
channels:
- conda-forge
- defaults
dependencies:
- backports.shutil_get_terminal_size=1.0.0=py35_1
- certifi=2016.2.28=py35_0
- cycler=0.10.0=py35_0
- dbus=1.10.10=0
- decorator=4.0.11=py35_0
- entrypoints=0.2.2=py35_0
- expat=2.1.0=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- ipykernel=4.5.2=py35_0
- ipython=5.1.0=py35_0
- ipython_genutils=0.1.0=py35_0
- jpeg=9b=0
- jsonschema=2.5.1=py35_0
- jupyter_client=4.4.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.2.1=py35_0
- libffi=3.2.1=1
- libiconv=1.14=0
- libsodium=1.0.10=0
- libxcb=1.12=1
- mistune=0.7.3=py35_0
- mpld3=0.2=py35_0
- mplexporter=0.0.1=py35_1
- nbconvert=4.2.0=py35_0
- nbformat=4.2.0=py35_0
- ncurses=5.9=10
- notebook=4.3.1=py35_0
- pandas=0.19.2=np111py35_1
- patsy=0.4.1=py35_0
- pexpect=4.2.1=py35_0
- prompt_toolkit=1.0.9=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_0
- python-dateutil=2.6.0=py35_0
- pytz=2016.10=py35_0
- pyzmq=16.0.2=py35_0
- requests=2.12.4=py35_0
- seaborn=0.7.1=py35_0
- setuptools=27.2.0=py35_0
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- terminado=0.6=py35_0
- tornado=4.4.2=py35_0
- tqdm=4.8.4=py35_0
- traitlets=4.3.1=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- zeromq=4.1.5=0
- zlib=1.2.8=3
- et_xmlfile=1.0.1=py35_0
- fontconfig=2.12.1=2
- freetype=2.5.5=2
- glib=2.50.2=1
- icu=54.1=0
- ipywidgets=5.2.2=py35_1
- jdcal=1.3=py35_0
- jinja2=2.9.4=py35_0
- jupyter=1.0.0=py35_3
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libpng=1.6.27=0
- libxml2=2.9.4=0
- markupsafe=0.23=py35_2
- matplotlib=2.0.0=np111py35_0
- mkl=2017.0.1=0
- numexpr=2.6.1=np111py35_2
- numpy=1.11.3=py35_0
- openssl=1.0.2j=0
- path.py=10.0=py35_0
- pcre=8.39=1
- pickleshare=0.7.4=py35_0
- pip=9.0.1=py35_1
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_2
- python=3.5.2=0
- qt=5.6.2=3
- qtconsole=4.2.1=py35_1
- readline=6.2=2
- scikit-learn=0.18.1=np111py35_1
- scipy=0.18.1=np111py35_1
- simplegeneric=0.8.1=py35_1
- statsmodels=0.6.1=np111py35_1
- tk=8.5.18=0
- widgetsnbextension=1.2.6=py35_0
- xlsxwriter=0.9.6=py35_0
- xz=5.2.2=1
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - et-xmlfile==1.0.1
  - hetio==0.2.3
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.1
  - prompt-toolkit==1.0.9
  - py2neo==3.1.2
  - xlrd==1.0.0
prefix: /home/ubuntu/anaconda3/envs/integrate

